name: Build and Release DSC Admin Console

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.5'

      - name: Build executable
        run: |
          go build -o DSC-Admin-Console.exe

      - name: Prepare release folder
        run: |
          mkdir release
          copy DSC-Admin-Console.exe release\
          xcopy db release\db /E /I
          xcopy web release\web /E /I
          xcopy templates release\templates /E /I

      - name: Upload release folder artifact
        uses: actions/upload-artifact@v6
        with:
          name: DSC-Admin-Console
          path: release/

  zip-powershell:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Zip PowerShell module
        run: |
          Compress-Archive -Path powershell\DSCPullServer\* -DestinationPath DSCPullServer.zip

      - name: Upload PowerShell artifact
        uses: actions/upload-artifact@v6
        with:
          name: DSCPullServer
          path: DSCPullServer.zip
